# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_texts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texts',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='server',
        ),
        migrations.AddField(
            model_name='profile',
            name='context',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='tribe',
            field=models.CharField(choices=[('h', '인간'), ('e', '엘프'), ('g', '자이언트')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
