# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170706_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tribe',
            new_name='race',
        ),
        migrations.AlterField(
            model_name='profile',
            name='server',
            field=models.CharField(choices=[('w', '울프'), ('m', '만돌린'), ('h', '하프'), ('l', '류트')], max_length=1),
        ),
    ]
