# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170717_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill_set',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
