# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170717_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='userimage/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(choices=[('근접 전투', '근접 전투'), ('랜스', '랜스'), ('궁술', '궁술'), ('마법', '마법'), ('격투술', '격투술'), ('연금술', '연금술'), ('올라운더', '올라운더')], max_length=50),
        ),
    ]
