# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170718_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
